### ISSUE TITLE
white screen on page load

### ISSUE THREAD

**Issue by hunterchen7** [ni554n/redium#2]
I ran into an issue where if I open an article and it loads in from the cache, it turns into a white page like so:
![image](https://github.com/ni554n/redium/assets/34012681/fff9c90e-a877-4acf-af9c-063ae81125fa)

but I fix it on my end by disabling JavaScript for the site, don't know if this is something worth baking into the extension itself?
![image](https://github.com/ni554n/redium/assets/34012681/4bee5ea6-b6e6-4236-9013-a53f098fbaf8)

**Comment by ni554n** [comment]
It's already been implemented. I don't use Brave myself, but it appears to be working as expected after I tested it on a fresh installation. Perhaps reinstalling the extension could help?

**Comment by hunterchen7** [comment]
I think it was my other extensions interfering with it so it's all good, thanks for the reply.
